services:
  - type: static
    name: gokul-portfolio
    buildCommand: npm run build
    publishPath: ./dist
    envVars:
      - key: VITE_WEB3FORMS_ACCESS_KEY
        sync: false # Set sync to false so you can safely configure/overwrite it in the UI
        value: 2e3a0800-8617-421b-ab86-13f613933356
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
